---
name: CI

'on':
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint-and-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        python-version:
          - "3.11"
          - "3.12"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # Keep LF line endings even on Windows runners
      - name: Normalize Git EOL
        run: git config --global core.autocrlf false

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix['python-version'] }}
          cache: pip

      - name: Install project + dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[test]"
          pip install pre-commit

      - name: Pre-commit (lint)
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Pytest
        run: pytest -q

      - name: Smoke scan example (allow findings)
        working-directory: examples/minimal-python
        continue-on-error: true
        run: python -m pqr.cli scan . --policy nist-stable

      - name: Upload report artifact (ubuntu-only)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: pqr-report-${{ matrix['python-version'] }}
          path: .pqr/report
          if-no-files-found: ignore

  build-wheel:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - name: Build wheel
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
